/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.MySQLManager;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Categoria;

/**
 *
 * @author MegaJoc
 */
public class vistaCategorias extends javax.swing.JFrame {

    DefaultTableModel tabla;

    /**
     * Creates new form vistaCategorias
     */
    ArrayList<Categoria> listaCategorias = new ArrayList<>();

    public vistaCategorias() {
        initComponents();
        mostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        categoriasTBL = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idCategoriaTXT = new javax.swing.JTextField();
        nombreCategoriaTXT = new javax.swing.JTextField();
        agregarCategoriaTXT = new javax.swing.JButton();
        eliminarCategoriaTXT = new javax.swing.JButton();
        editarCategoriaTXT = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        categoriasTBL.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null},
                    {null, null},
                    {null, null},
                    {null, null}
                },
                new String[]{
                    "Id de categoría", "Nombre de categoría"
                }
        ));
        jScrollPane1.setViewportView(categoriasTBL);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Menú de categorías");

        jLabel2.setText("Id de categoría");

        jLabel3.setText("Nombre de categoría");

        idCategoriaTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idCategoriaTXTKeyTyped(evt);
            }
        });

        nombreCategoriaTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreCategoriaTXTKeyTyped(evt);
            }
        });

        agregarCategoriaTXT.setText("Agregar nueva categoría");
        agregarCategoriaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCategoriaTXTActionPerformed(evt);
            }
        });

        eliminarCategoriaTXT.setText("Eliminar categoría");
        eliminarCategoriaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCategoriaTXTActionPerformed(evt);
            }
        });

        editarCategoriaTXT.setText("Editar categoría");
        editarCategoriaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCategoriaTXTActionPerformed(evt);
            }
        });

        jButton4.setText("Finalizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(agregarCategoriaTXT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nombreCategoriaTXT, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(idCategoriaTXT, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(eliminarCategoriaTXT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(editarCategoriaTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel1)
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(idCategoriaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(19, 19, 19)
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(nombreCategoriaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(agregarCategoriaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(editarCategoriaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eliminarCategoriaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarCategoriaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCategoriaTXTActionPerformed
        if (confirmaTextField()) {
            String nom_cat = nombreCategoriaTXT.getText().toUpperCase();

            Categoria c = new Categoria(nom_cat);
            c.agregarCategoria(nom_cat);

            limpiar();
            mostrarTabla();

            JOptionPane.showMessageDialog(new JFrame(), "Categoría agregada satisfactoriamente");

        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Complete todos los campos por favor");

        }
    }//GEN-LAST:event_agregarCategoriaTXTActionPerformed

    private void editarCategoriaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCategoriaTXTActionPerformed
        if (confirmaTextField()) {
            int id_cat;

            id_cat = Integer.parseInt(idCategoriaTXT.getText());
            String nom_cat = nombreCategoriaTXT.getText().toUpperCase();

            Categoria c = new Categoria(id_cat, nom_cat);
            c.actualizarCategoria(id_cat, nom_cat);
            limpiar();
            mostrarTabla();
            JOptionPane.showMessageDialog(new JFrame(), "Categoria editada satisfactoriamente");

        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Complete todos los campos por favor");

        }
    }//GEN-LAST:event_editarCategoriaTXTActionPerformed

    public void mostrarTabla() {
        listaCategorias.removeAll(listaCategorias);
        categoriasTBL.setModel(new javax.swing.table.DefaultTableModel());
        MySQLManager manager = new MySQLManager("localhost", "3306", "bibliotecafastdevelopment", "root", "");
        manager.executeQueryConsultaLLenaTablaCategoria(listaCategorias);
        tabla = new DefaultTableModel();
        tabla.addColumn("Id categoria");
        tabla.addColumn("Nombre Categoria");
        //Consultamos la cantidad de filas de la lista
        tabla.setRowCount(listaCategorias.size());         
        /*Efectuamos un recorrido al ArrayList para agregar
        cada fila de este a el objeto DefaultTableModel (tabla) */
        int i = 0;
        for (Categoria cat : listaCategorias) {
        /*Incorporamos en la fila y columna respectiva del 
        modelo el dato obtenido desde la lista */
            tabla.setValueAt(cat.getId_cat(), i, 0);
            tabla.setValueAt(cat.getNom_cat(), i, 1);
            i++;
        }
        //Incorporamos a la tabla (Jtable) el modelo de datos creado (DefaultTableModel)
        categoriasTBL.setModel(tabla);

    }

    private boolean confirmaTextField() {
        boolean nom_cat = false;
        int contver = 0;

        nom_cat = nombreCategoriaTXT.getText().isEmpty();

        boolean[] arraytxt = new boolean[]{nom_cat};
        for (boolean elemento : arraytxt) {
            if (elemento == true) {

            } else {
                contver++;

            }

        }
        return contver == 1;

    }

    private void limpiar() {
        nombreCategoriaTXT.setText("");
    }

    private void eliminarCategoriaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCategoriaTXTActionPerformed
        listaCategorias.removeAll(listaCategorias);
        int id_cat;
        id_cat = Integer.parseInt(idCategoriaTXT.getText());
        Categoria c = new Categoria();
        c.borrarCategoria(id_cat);
        mostrarTabla();
    }//GEN-LAST:event_eliminarCategoriaTXTActionPerformed

    private void idCategoriaTXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idCategoriaTXTKeyTyped
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_idCategoriaTXTKeyTyped

    private void nombreCategoriaTXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreCategoriaTXTKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c > ' ') && (c < 'á' || c > 'ú') && (c < 'Á' || c > 'Ú')) {
            evt.consume();
        }
    }//GEN-LAST:event_nombreCategoriaTXTKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarCategoriaTXT;
    private javax.swing.JTable categoriasTBL;
    private javax.swing.JButton editarCategoriaTXT;
    private javax.swing.JButton eliminarCategoriaTXT;
    private javax.swing.JTextField idCategoriaTXT;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreCategoriaTXT;
    // End of variables declaration//GEN-END:variables
}
