/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.MySQLManager;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Idioma;

/**
 *
 * @author MegaJoc
 */
public class vistaIdiomas extends javax.swing.JFrame {

    /**
     * Creates new form vistaEditorial
     */
    ArrayList<Idioma> listaIdiomas = new ArrayList<>();
    
    public vistaIdiomas(){
        initComponents();
        mostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idIdiomaTXT = new javax.swing.JTextField();
        finalizarIdiomaBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        idiomaTBL = new javax.swing.JTable();
        editarIdiomaBTN = new javax.swing.JButton();
        agregarIdiomaNuevoBTN = new javax.swing.JButton();
        eliminarIdiomaBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nuevoIdiomaTXT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Menú de idiomas");

        jLabel2.setText("Idioma a agregar");

        finalizarIdiomaBTN.setText("Finalizar");

        idiomaTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Id de idioma", "Idioma"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(idiomaTBL);

        editarIdiomaBTN.setText("Editar");
        editarIdiomaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarIdiomaBTNActionPerformed(evt);
            }
        });

        agregarIdiomaNuevoBTN.setText("Agregar idioma nuevo");
        agregarIdiomaNuevoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarIdiomaNuevoBTNActionPerformed(evt);
            }
        });

        eliminarIdiomaBTN.setText("Eliminar");
        eliminarIdiomaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarIdiomaBTNActionPerformed(evt);
            }
        });

        jLabel4.setText("Id idioma");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editarIdiomaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(finalizarIdiomaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idIdiomaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevoIdiomaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(agregarIdiomaNuevoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eliminarIdiomaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idIdiomaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(nuevoIdiomaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarIdiomaNuevoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminarIdiomaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarIdiomaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalizarIdiomaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarIdiomaNuevoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarIdiomaNuevoBTNActionPerformed
            if (confirmaTextField()) {
            String nom_idioma = nuevoIdiomaTXT.getText().toUpperCase();

            Idioma i = new Idioma(nom_idioma);
            i.agregarIdioma(nom_idioma);

            limpiar();
            mostrarTabla();

            JOptionPane.showMessageDialog(new JFrame(), "Idioma agregado satisfactoriamente");

        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Complete todos los campos por favor");

       }
    }//GEN-LAST:event_agregarIdiomaNuevoBTNActionPerformed

    private void eliminarIdiomaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarIdiomaBTNActionPerformed
        limpiarTabla();
        int id_idioma;
        id_idioma = Integer.parseInt(idIdiomaTXT.getText());
        Idioma i = new Idioma();
        i.borrarIdioma(id_idioma);
        mostrarTabla();
    }//GEN-LAST:event_eliminarIdiomaBTNActionPerformed
    
    public void mostrarTabla() {
        limpiarTabla();
        MySQLManager manager = new MySQLManager("localhost", "3306", "bibliotecafastdevelopment", "root", "");
        manager.executeQueryConsultaLLenaTablaIdioma(listaIdiomas);
        String matriz[][] = new String[listaIdiomas.size()][2];

        for (int i = 0; i < listaIdiomas.size(); i++) {

            String idIdioma = Integer.toString(listaIdiomas.get(i).getId_idioma());

            matriz[i][0] = idIdioma;
            matriz[i][1] = listaIdiomas.get(i).getNom_idioma();

        }
        idiomaTBL.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "Id de idioma", "Idioma"
                }
        ));

    }
    
    public void limpiarTabla() {
        for (int i = 0; i < listaIdiomas.size(); i++) {
            listaIdiomas.remove(i);
        }
               
    }
    
    private boolean confirmaTextField() {
        boolean nom_idioma = false;
        int contver = 0;

        nom_idioma = nuevoIdiomaTXT.getText().isEmpty();


        boolean[] arraytxt = new boolean[]{nom_idioma};
        for (boolean elemento : arraytxt) {
            if (elemento == true) {

            } else {
                contver++;

            }

        }
        return contver == 1;

    }
    
    private void limpiar() {
        nuevoIdiomaTXT.setText("");
    }
    
    private void editarIdiomaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarIdiomaBTNActionPerformed
        if (confirmaTextField()){
            int id_idioma;
            
            id_idioma = Integer.parseInt(idIdiomaTXT.getText());
            String nom_idioma = nuevoIdiomaTXT.getText().toUpperCase();

            Idioma i = new Idioma(id_idioma, nom_idioma);
            i.actualizarIdioma(id_idioma, nom_idioma);
            limpiar();
            mostrarTabla();
            JOptionPane.showMessageDialog(new JFrame(), "Idioma editado satisfactoriamente");

        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Complete todos los campos por favor");

        }
    }//GEN-LAST:event_editarIdiomaBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaIdiomas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarIdiomaNuevoBTN;
    private javax.swing.JButton editarIdiomaBTN;
    private javax.swing.JButton eliminarIdiomaBTN;
    private javax.swing.JButton finalizarIdiomaBTN;
    private javax.swing.JTextField idIdiomaTXT;
    private javax.swing.JTable idiomaTBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nuevoIdiomaTXT;
    // End of variables declaration//GEN-END:variables
}
